### ISSUE TITLE
Training set generation script

### ISSUE THREAD

**Issue by bloodbare** [Softcatala/nmt-softcatala#3]
Is there any script that generates the training set from public softcatala repositories?

**Comment by jordimas** [comment]
Hi,

The source code data is at: https://www.softcatala.org/pub/softcatala/opennmt/training-sets/

The "get.sh" scripts at:

https://github.com/Softcatala/nmt-softcatala/tree/master/training-sets

download the corpus and "preprocess.sh" does all the data cleaning and transformation. 

The sc-memories model is very simple since it's a single source but the generic 'eng-cat' is more complicated since it's from different sources.

If you have problems please ask, not much people has tested this. We are also always looking for help on this area.

Regards

Jordi,

**Comment by bloodbare** [comment]
Sorry, I meant how to generate the corpus, in case I want to generate from another set of languages.

**Comment by jordimas** [comment]
For each language pair you need to select an adequate sources for your corpus. 

You can check here https://github.com/Softcatala/en-ca-corpus the sources that we use for English - Catalan and see if they have aligned corpus in the pair of languages that you are looking for.

Consider that for training you will need a GPU running for serveral days. We use p3x.large instances from Amazon.

What language pair are you looking into?

**Comment by bloodbare** [comment]
I was looking to es-ca to push on a T5 model. We use to train with GPUs and TPUs so no problem, thanks!

**Comment by jordimas** [comment]
There is a lot ca-es corpus avaiable. Check the references that I shared with you.

Before starting building a neural network model for ca-es I will check how Google and other compare to Apertium. Since Spanish and Catalan are latin languages (closely related), it's possible that Apertium (whom has a great ca-es support) outperforms what you can build.  I will do an analysis first (this is what I actually did also: https://twitter.com/jordimash/status/1216797368273768448)
